const listPercent = [
    {
        title: '100% DE DESCUENTO',
        list: [
            'Consulta de Urgencia',
            'Consulta odontologia general',
            'Profilaxis simple + fluor',

        ],
    },
    {
        title: '80% DE DESCUENTO',
        list: [
            'Sutura'
        ],
    },
    {
        title: '60% DE DESCUENTO',
        list: [
            'Amalgama(1 superficie)',
            'Amalgama(2 superficies)',
            'Amalgama(3 o más superficies)',
            'Blanqueamiento dental completo',
        ],
    },
    {
        title: '55% DE DESCUENTO',
        list: [
            'Exodoncia diente incluido',
            'Resina compuesta',
        ],
    },
    {
        title: '50% DE DESCUENTO',
        list: [
            'Ajuste oclusal',
            'Amalgama compuesta',
            'Amalgapin',
            'Base cavitaria Dycal',
            'Base cavitaria fotocurable',
            'Base cavitaria ionomero',
            'Blanqueamiento (1 diente)',
            'Carillas de resina',
            'CL Resina (1 superficie)',
            'CL Resina (2 superficies)',
            'CL Resina (3 superficies)',
            'CL Resina (4 o más superficies)',
            'Control de ortodoncia mensual',
            'Control de ortodoncia quincenal',
            'Emergencia',
            'Exodoncia compleja',
            'Exodoncia semicompleja',
            'Exodoncias simples (adicionales)',
            'Incrustación de resina',
            'Juego radiográfico',
            'Montaje en marco radiografico',
            'Profilaxis con Prophymate',
            'Pulido de amalgama',
            'Radiografias cefalometricas',
            'Radiografias panoramicas',
            'Radiografias periapicales',
            'Reconstrucción con resina',
            'Reconstrucción estética con resina',
            'Remoción de manchas con AIR FLOW',
            'Tratamiento temporal base',

        ],
    },
    {
        title: '40% DE DESCUENTO',
        list: [
            'Frenoctomía',
            'Modelos de yeso(c / u)',
            'Raspado y alisado',
            'Tratamiento de ortodoncia',
        ],
    },
    {
        title: '30% DE DESCUENTO',
        list: [
            'Ameloplastía resina',
            'Ameloplastía sellante',
            'Aparato de ortodoncia',
            'Apexificación',
            'Apicectomía anterior',
            'Apicectomía molar',
            'Apicectomía premolar',
            'Caja plastica para retenedor',
            'Cambio de liga',
            'Colocación de bracket cerámica',
            'Colocación de bracket porcelana',
            'Colocación de bracket Zafiro',
            'Colocación de freno superior - inferior',
            'Consulta de ortodoncia ',
            'Consultas especializada',
            'Control de aparato fijo - removible en niños',
            'Control de movimiento fijo',
            'Control de movimiento removible',
            'Control de prótesis',
            'Control de pulpotomía',
            'Endodoncia anterior',
            'Endodoncia molar',
            'Endodoncia premolar',
            'Extracción deciduo(anterior o posterior)',
            'Jeringa de blanqueamiento',
            'Pulpectomía',
            'Pulpotomía',
            'Recontorneo estético de dientes anteriores(c / u)',
            'Re - endodoncia anterior',
            'Re - endodoncia molar',
            'Re - endodoncia premolar',
            'Remoción de aparatología',
            'Remoción de bracket(1 arcada)',
            'Remoción de bracket parcial',
            'Remoción de bracket superior e inferior',
            'Retenedor fijo',
            'Retenedor removible Hawlay',
            'Sellante fisura adulto',
            'Sellantes',
            'Tratamiento de ortodoncia(1 arcada)',
        ],
        exception: 'En caso de urgencia la endodoncia sera cubierta en un 100% *'
    },
    {
        title: '25% DE DESCUENTO',
        list: [
            'Cementación de banda',
            'Consulta odontopediatría',
            'Drenaje de absceso',
            'Perdida de arco',
            'Profilaxis infantil',
            'Prótesis removible(superior o inferior)',
            'Reparación de bracket',
            'Reparación de bracket estético perdido',
            'Reparación de bracket perdido',
        ],
    },
    {
        title: '20% DE DESCUENTO',
        list: [
            'Alagramiento de corona',
            'Aleta Maryland',
            'Amputación radicular',
            'Biopsia(laboratorio)',
            'Carilla de porcelana',
            'Cementación aparato - corona',
            'Cirugia aérea edéntula',
            'Cirugía de torus lingual(por cuadrante)',
            'Cirugía estética periodontal',
            'Cirugía exploratoria',
            'Cirugia mucogingival',
            'Cirugia ósea(resección y remod ',
            'Control de férula',
            'Corona cerómeno',
            'Corona completa en metal(acero inoxidable)',
            'Corona de porcelana pura',
            'Corona metal porcelana',
            'Corona sobre implantes',
            'Corona temporal',
            'Drenaje de absceso',
            'Exodoncia 3ra.molar erupcionada',
            'Exodoncia 3ra.molar incluida',
            'Exodoncia 3ra.molar retenida',
            'Exodoncia 3ra.molar semi incluida',
            'Férula',
            'Gingivectomía(cada diente)',
            'Gingivectomía(por cuadrante)',
            'Hemisección',
            'Implantes',
            'Injerto gingival libre',
            'Injerto óseo',
            'Jaula',
            'Mantenedor con espacio bilateral',
            'Mantenedor con espacio unilateral',
            'Mantenedor con frente removoble estético',
            'Mantenimiento periodontal',
            'Mucocele y ranula',
            'Muñón',
            'Pernos(cada uno)',
            'Placas oclusales',
            'Procedimiento de cuña distal',
            'Procedimiento por colgajo periodontico',
            'Prótesis asistencial',
            'Prótesis parcial flex',
            'Prótesis total(superior o inferior)',
            'Prótesis Valplast',
            'Provisionales(por unidad)',
            'Rebase',
            'Reparacion en consultorio',
            'Reparacion en laboratorio',
            'Reparación ósea guiada',
            'Splint',
            'Tornillo de cicatrización',
            'Tratamiento paliativo',
            'Ventana para exploración de diente',
            'Ventana quirúrgica en niños',
        ],
    }
]

export default listPercent